# This is a basic workflow to help you get started with Actions

name: ZAP-DEV

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zap_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: OWASP ZAP Baseline Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-baseline@acd8e997263688cb49cb5ff8247a4b2758c548ab
        uses: zaproxy/action-baseline@v0.4.0
        with:
          issue_title:  ZAP Scan Baseline Report
          # GitHub Token to create issues in the repository
          token: ${{ github.token }}
          # Target URL
          ##target: https://selfservice-dev.apps.silver.devops.gov.bc.ca
          target: https://developer.iddev.gov.bc.ca
          # Relative path of the ZAP configuration file
          rules_file_name: # optional
          # The Docker file to be executed
          docker_name: 'owasp/zap2docker-stable'
          # Additional command line options
          cmd_options: # optional
          # The title for the GitHub issue to be created
          issue_title: # optional, default is ZAP Scan Baseline Report
          # The action status will be set to fail if ZAP identifies any alerts during the baseline scan
          fail_action: # optional
